# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'boardgui_2.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QWidget)

class Ui_board_widget(object):
    def setupUi(self, board_widget):
        if not board_widget.objectName():
            board_widget.setObjectName(u"board_widget")
        board_widget.resize(828, 608)
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        board_widget.setPalette(palette)
        board_widget.setStyleSheet(u"background-color: transparent;")
        self.label = QLabel(board_widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 400, 400))
        self.label.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.label.setPixmap(QPixmap(u"~/Desktop/climbing_board/led_board/data/board.jpg"))
        self.label.setScaledContents(True)
        self.hold44 = QPushButton(board_widget)
        self.hold44.setObjectName(u"hold44")
        self.hold44.setGeometry(QRect(70, 40, 81, 24))
        palette1 = QPalette()
        brush1 = QBrush(QColor(255, 255, 255, 0))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold44.setPalette(palette1)
        self.hold44.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold44.setCheckable(True)
        self.hold21 = QPushButton(board_widget)
        self.hold21.setObjectName(u"hold21")
        self.hold21.setGeometry(QRect(320, 40, 16, 16))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold21.setPalette(palette2)
        self.hold21.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold21.setCheckable(True)
        self.hold22 = QPushButton(board_widget)
        self.hold22.setObjectName(u"hold22")
        self.hold22.setGeometry(QRect(220, 10, 61, 16))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold22.setPalette(palette3)
        self.hold22.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold22.setCheckable(True)
        self.hold23 = QPushButton(board_widget)
        self.hold23.setObjectName(u"hold23")
        self.hold23.setGeometry(QRect(240, 70, 31, 16))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold23.setPalette(palette4)
        self.hold23.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold23.setCheckable(True)
        self.hold25 = QPushButton(board_widget)
        self.hold25.setObjectName(u"hold25")
        self.hold25.setGeometry(QRect(180, 50, 16, 16))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold25.setPalette(palette5)
        self.hold25.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold25.setCheckable(True)
        self.hold26 = QPushButton(board_widget)
        self.hold26.setObjectName(u"hold26")
        self.hold26.setGeometry(QRect(300, 110, 16, 16))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold26.setPalette(palette6)
        self.hold26.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold26.setCheckable(True)
        self.hold27 = QPushButton(board_widget)
        self.hold27.setObjectName(u"hold27")
        self.hold27.setGeometry(QRect(330, 140, 16, 16))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold27.setPalette(palette7)
        self.hold27.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold27.setCheckable(True)
        self.hold24 = QPushButton(board_widget)
        self.hold24.setObjectName(u"hold24")
        self.hold24.setGeometry(QRect(40, 20, 41, 16))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold24.setPalette(palette8)
        self.hold24.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold24.setCheckable(True)
        self.hold2 = QPushButton(board_widget)
        self.hold2.setObjectName(u"hold2")
        self.hold2.setGeometry(QRect(170, 130, 31, 16))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold2.setPalette(palette9)
        self.hold2.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold2.setCheckable(True)
        self.hold3 = QPushButton(board_widget)
        self.hold3.setObjectName(u"hold3")
        self.hold3.setGeometry(QRect(190, 100, 16, 16))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold3.setPalette(palette10)
        self.hold3.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold3.setCheckable(True)
        self.hold4 = QPushButton(board_widget)
        self.hold4.setObjectName(u"hold4")
        self.hold4.setGeometry(QRect(90, 180, 31, 16))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold4.setPalette(palette11)
        self.hold4.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold4.setCheckable(True)
        self.hold5 = QPushButton(board_widget)
        self.hold5.setObjectName(u"hold5")
        self.hold5.setGeometry(QRect(40, 20, 41, 16))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold5.setPalette(palette12)
        self.hold5.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold5.setCheckable(True)
        self.hold6 = QPushButton(board_widget)
        self.hold6.setObjectName(u"hold6")
        self.hold6.setGeometry(QRect(190, 170, 16, 16))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold6.setPalette(palette13)
        self.hold6.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold6.setCheckable(True)
        self.hold7 = QPushButton(board_widget)
        self.hold7.setObjectName(u"hold7")
        self.hold7.setGeometry(QRect(100, 120, 21, 16))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold7.setPalette(palette14)
        self.hold7.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold7.setCheckable(True)
        self.hold8 = QPushButton(board_widget)
        self.hold8.setObjectName(u"hold8")
        self.hold8.setGeometry(QRect(240, 180, 21, 16))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold8.setPalette(palette15)
        self.hold8.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold8.setCheckable(True)
        self.hold9 = QPushButton(board_widget)
        self.hold9.setObjectName(u"hold9")
        self.hold9.setGeometry(QRect(320, 250, 21, 16))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette16.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette16.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette16.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette16.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette16.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette16.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold9.setPalette(palette16)
        self.hold9.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold9.setCheckable(True)
        self.hold54 = QPushButton(board_widget)
        self.hold54.setObjectName(u"hold54")
        self.hold54.setGeometry(QRect(280, 230, 21, 16))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette17.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette17.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold54.setPalette(palette17)
        self.hold54.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold54.setCheckable(True)
        self.hold55 = QPushButton(board_widget)
        self.hold55.setObjectName(u"hold55")
        self.hold55.setGeometry(QRect(280, 280, 16, 16))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette18.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette18.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold55.setPalette(palette18)
        self.hold55.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold55.setCheckable(True)
        self.hold12 = QPushButton(board_widget)
        self.hold12.setObjectName(u"hold12")
        self.hold12.setGeometry(QRect(170, 240, 41, 16))
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette19.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette19.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette19.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette19.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold12.setPalette(palette19)
        self.hold12.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold12.setCheckable(True)
        self.hold13 = QPushButton(board_widget)
        self.hold13.setObjectName(u"hold13")
        self.hold13.setGeometry(QRect(130, 200, 16, 16))
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette20.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette20.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette20.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette20.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette20.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette20.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette20.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette20.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold13.setPalette(palette20)
        self.hold13.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold13.setCheckable(True)
        self.hold14 = QPushButton(board_widget)
        self.hold14.setObjectName(u"hold14")
        self.hold14.setGeometry(QRect(80, 280, 31, 16))
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette21.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette21.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette21.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette21.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette21.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette21.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette21.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette21.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold14.setPalette(palette21)
        self.hold14.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold14.setCheckable(True)
        self.hold15 = QPushButton(board_widget)
        self.hold15.setObjectName(u"hold15")
        self.hold15.setGeometry(QRect(150, 110, 21, 21))
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette22.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette22.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette22.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette22.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette22.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette22.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette22.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette22.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold15.setPalette(palette22)
        self.hold15.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold15.setCheckable(True)
        self.hold16 = QPushButton(board_widget)
        self.hold16.setObjectName(u"hold16")
        self.hold16.setGeometry(QRect(80, 310, 31, 16))
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette23.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette23.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette23.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette23.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette23.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette23.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette23.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette23.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold16.setPalette(palette23)
        self.hold16.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold16.setCheckable(True)
        self.hold17 = QPushButton(board_widget)
        self.hold17.setObjectName(u"hold17")
        self.hold17.setGeometry(QRect(180, 330, 41, 21))
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette24.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette24.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette24.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette24.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette24.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette24.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette24.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette24.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold17.setPalette(palette24)
        self.hold17.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold17.setCheckable(True)
        self.hold18 = QPushButton(board_widget)
        self.hold18.setObjectName(u"hold18")
        self.hold18.setGeometry(QRect(240, 220, 16, 16))
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette25.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette25.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette25.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette25.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette25.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette25.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette25.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette25.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold18.setPalette(palette25)
        self.hold18.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold18.setCheckable(True)
        self.hold19 = QPushButton(board_widget)
        self.hold19.setObjectName(u"hold19")
        self.hold19.setGeometry(QRect(270, 330, 16, 16))
        palette26 = QPalette()
        palette26.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette26.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette26.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette26.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette26.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette26.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette26.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette26.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette26.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold19.setPalette(palette26)
        self.hold19.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold19.setCheckable(True)
        self.hold20 = QPushButton(board_widget)
        self.hold20.setObjectName(u"hold20")
        self.hold20.setGeometry(QRect(140, 320, 16, 16))
        palette27 = QPalette()
        palette27.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette27.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette27.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette27.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette27.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette27.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette27.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette27.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette27.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold20.setPalette(palette27)
        self.hold20.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold20.setCheckable(True)
        self.hold47 = QPushButton(board_widget)
        self.hold47.setObjectName(u"hold47")
        self.hold47.setGeometry(QRect(170, 20, 16, 16))
        palette28 = QPalette()
        palette28.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette28.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette28.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette28.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette28.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette28.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette28.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette28.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette28.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold47.setPalette(palette28)
        self.hold47.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold47.setCheckable(True)
        self.hold48 = QPushButton(board_widget)
        self.hold48.setObjectName(u"hold48")
        self.hold48.setGeometry(QRect(310, 70, 16, 16))
        palette29 = QPalette()
        palette29.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette29.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette29.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette29.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette29.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette29.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette29.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette29.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette29.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold48.setPalette(palette29)
        self.hold48.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold48.setCheckable(True)
        self.hold49 = QPushButton(board_widget)
        self.hold49.setObjectName(u"hold49")
        self.hold49.setGeometry(QRect(330, 30, 16, 16))
        palette30 = QPalette()
        palette30.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette30.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette30.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette30.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette30.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette30.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette30.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette30.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette30.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold49.setPalette(palette30)
        self.hold49.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold49.setCheckable(True)
        self.hold50 = QPushButton(board_widget)
        self.hold50.setObjectName(u"hold50")
        self.hold50.setGeometry(QRect(320, 190, 16, 16))
        palette31 = QPalette()
        palette31.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette31.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette31.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette31.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette31.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette31.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette31.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette31.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette31.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold50.setPalette(palette31)
        self.hold50.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold50.setCheckable(True)
        self.hold51 = QPushButton(board_widget)
        self.hold51.setObjectName(u"hold51")
        self.hold51.setGeometry(QRect(310, 70, 16, 16))
        palette32 = QPalette()
        palette32.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette32.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette32.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette32.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette32.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette32.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette32.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette32.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette32.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold51.setPalette(palette32)
        self.hold51.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold51.setCheckable(True)
        self.hold46 = QPushButton(board_widget)
        self.hold46.setObjectName(u"hold46")
        self.hold46.setGeometry(QRect(200, 290, 41, 21))
        palette33 = QPalette()
        palette33.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette33.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette33.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette33.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette33.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette33.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette33.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette33.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette33.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold46.setPalette(palette33)
        self.hold46.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold46.setCheckable(True)
        self.hold38 = QPushButton(board_widget)
        self.hold38.setObjectName(u"hold38")
        self.hold38.setGeometry(QRect(320, 310, 16, 16))
        palette34 = QPalette()
        palette34.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette34.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette34.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette34.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette34.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette34.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette34.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette34.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette34.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold38.setPalette(palette34)
        self.hold38.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold38.setCheckable(True)
        self.hold39 = QPushButton(board_widget)
        self.hold39.setObjectName(u"hold39")
        self.hold39.setGeometry(QRect(230, 250, 16, 16))
        palette35 = QPalette()
        palette35.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette35.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette35.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette35.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette35.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette35.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette35.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette35.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette35.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold39.setPalette(palette35)
        self.hold39.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold39.setCheckable(True)
        self.hold40 = QPushButton(board_widget)
        self.hold40.setObjectName(u"hold40")
        self.hold40.setGeometry(QRect(210, 270, 16, 16))
        palette36 = QPalette()
        palette36.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette36.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette36.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette36.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette36.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette36.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette36.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette36.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette36.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold40.setPalette(palette36)
        self.hold40.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold40.setCheckable(True)
        self.hold41 = QPushButton(board_widget)
        self.hold41.setObjectName(u"hold41")
        self.hold41.setGeometry(QRect(70, 240, 16, 16))
        palette37 = QPalette()
        palette37.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette37.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette37.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette37.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette37.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette37.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette37.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette37.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette37.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold41.setPalette(palette37)
        self.hold41.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold41.setCheckable(True)
        self.hold42 = QPushButton(board_widget)
        self.hold42.setObjectName(u"hold42")
        self.hold42.setGeometry(QRect(150, 270, 20, 20))
        palette38 = QPalette()
        palette38.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette38.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette38.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette38.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette38.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette38.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette38.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette38.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette38.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold42.setPalette(palette38)
        self.hold42.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold42.setCheckable(True)
        self.hold43 = QPushButton(board_widget)
        self.hold43.setObjectName(u"hold43")
        self.hold43.setGeometry(QRect(190, 150, 16, 16))
        palette39 = QPalette()
        palette39.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette39.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette39.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette39.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette39.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette39.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette39.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette39.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette39.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold43.setPalette(palette39)
        self.hold43.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold43.setCheckable(True)
        self.hold45 = QPushButton(board_widget)
        self.hold45.setObjectName(u"hold45")
        self.hold45.setGeometry(QRect(190, 200, 16, 16))
        palette40 = QPalette()
        palette40.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette40.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette40.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette40.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette40.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette40.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette40.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette40.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette40.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold45.setPalette(palette40)
        self.hold45.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold45.setCheckable(True)
        self.hold52 = QPushButton(board_widget)
        self.hold52.setObjectName(u"hold52")
        self.hold52.setGeometry(QRect(160, 160, 16, 16))
        palette41 = QPalette()
        palette41.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette41.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette41.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette41.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette41.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette41.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette41.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette41.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette41.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold52.setPalette(palette41)
        self.hold52.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold52.setCheckable(True)
        self.hold53 = QPushButton(board_widget)
        self.hold53.setObjectName(u"hold53")
        self.hold53.setGeometry(QRect(110, 240, 41, 16))
        palette42 = QPalette()
        palette42.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette42.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette42.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette42.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette42.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette42.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette42.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette42.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette42.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold53.setPalette(palette42)
        self.hold53.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold53.setCheckable(True)
        self.hold28 = QPushButton(board_widget)
        self.hold28.setObjectName(u"hold28")
        self.hold28.setGeometry(QRect(120, 160, 16, 16))
        palette43 = QPalette()
        palette43.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette43.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette43.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette43.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette43.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette43.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette43.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette43.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette43.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold28.setPalette(palette43)
        self.hold28.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold28.setCheckable(True)
        self.hold29 = QPushButton(board_widget)
        self.hold29.setObjectName(u"hold29")
        self.hold29.setGeometry(QRect(90, 140, 16, 16))
        palette44 = QPalette()
        palette44.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette44.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette44.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette44.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette44.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette44.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette44.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette44.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette44.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold29.setPalette(palette44)
        self.hold29.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold29.setCheckable(True)
        self.hold30 = QPushButton(board_widget)
        self.hold30.setObjectName(u"hold30")
        self.hold30.setGeometry(QRect(30, 160, 16, 16))
        palette45 = QPalette()
        palette45.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette45.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette45.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette45.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette45.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette45.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette45.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette45.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette45.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold30.setPalette(palette45)
        self.hold30.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold30.setCheckable(True)
        self.hold31 = QPushButton(board_widget)
        self.hold31.setObjectName(u"hold31")
        self.hold31.setGeometry(QRect(280, 190, 16, 16))
        palette46 = QPalette()
        palette46.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette46.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette46.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette46.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette46.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette46.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette46.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette46.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette46.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold31.setPalette(palette46)
        self.hold31.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold31.setCheckable(True)
        self.hold32 = QPushButton(board_widget)
        self.hold32.setObjectName(u"hold32")
        self.hold32.setGeometry(QRect(210, 130, 16, 16))
        palette47 = QPalette()
        palette47.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette47.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette47.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette47.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette47.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette47.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette47.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette47.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette47.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold32.setPalette(palette47)
        self.hold32.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold32.setCheckable(True)
        self.hold33 = QPushButton(board_widget)
        self.hold33.setObjectName(u"hold33")
        self.hold33.setGeometry(QRect(30, 90, 20, 20))
        palette48 = QPalette()
        palette48.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette48.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette48.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette48.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette48.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette48.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette48.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette48.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette48.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold33.setPalette(palette48)
        self.hold33.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold33.setCheckable(True)
        self.hold34 = QPushButton(board_widget)
        self.hold34.setObjectName(u"hold34")
        self.hold34.setGeometry(QRect(280, 130, 16, 16))
        palette49 = QPalette()
        palette49.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette49.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette49.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette49.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette49.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette49.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette49.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette49.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette49.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold34.setPalette(palette49)
        self.hold34.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold34.setCheckable(True)
        self.hold35 = QPushButton(board_widget)
        self.hold35.setObjectName(u"hold35")
        self.hold35.setGeometry(QRect(240, 120, 16, 16))
        palette50 = QPalette()
        palette50.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette50.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette50.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette50.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette50.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette50.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette50.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette50.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette50.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold35.setPalette(palette50)
        self.hold35.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold35.setCheckable(True)
        self.hold37 = QPushButton(board_widget)
        self.hold37.setObjectName(u"hold37")
        self.hold37.setGeometry(QRect(110, 80, 16, 16))
        palette51 = QPalette()
        palette51.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette51.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette51.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette51.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette51.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette51.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette51.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette51.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette51.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.hold37.setPalette(palette51)
        self.hold37.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"    border: none;")
        self.hold37.setCheckable(True)

        self.retranslateUi(board_widget)

        QMetaObject.connectSlotsByName(board_widget)
    # setupUi

    def retranslateUi(self, board_widget):
        board_widget.setWindowTitle(QCoreApplication.translate("board_widget", u"Form", None))
        self.label.setText("")
        self.hold44.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold21.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold22.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold23.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold25.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold26.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold27.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold24.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold2.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold3.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold4.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold5.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold6.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold7.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold8.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold9.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold54.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold55.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold12.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold13.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold14.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold15.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold16.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold17.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold18.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold19.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold20.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold47.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold48.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold49.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold50.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold51.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold46.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold38.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold39.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold40.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold41.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold42.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold43.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold45.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold52.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold53.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold28.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold29.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold30.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold31.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold32.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold33.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold34.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold35.setText(QCoreApplication.translate("board_widget", u"...", None))
        self.hold37.setText(QCoreApplication.translate("board_widget", u"...", None))
    # retranslateUi

